---
- hosts: all
  become: yes
  roles:
    - common_kubeadm/containerd
    - common_kubeadm/kube
    - common_kubeadm/controlplane
  vars_prompt:
    - name: "controlplane_public_ip"
      prompt: "controlplaneノードのパブリックIPアドレスを入力"
      private: no
